### ISSUE TITLE
docker服务不启动问题

### ISSUE THREAD

**Issue by MaxSecurity** [huisunan/epic4j#28]
运行docker run -d -v ~/epic4j:/opt/epic4j/config --name myepic huisunan/epic4j:latest 命令docker不运行

挂在目录也改成自己自定义的了

**Comment by insoxin** [comment]
啊这,没docker基础,就本地搭建吧

**Comment by huisunan** [comment]
https://www.runoob.com/docker/centos-docker-install.html

**Comment by MaxSecurity** [comment]
> 运行docker run -d -v ~/epic4j:/opt/epic4j/config --name myepic huisunan/epic4j:latest 命令docker不运行
> 
> 挂在目录也改成自己自定义的了
